theme = "base16_transparent"

[editor]
line-number = "relative"
scroll-lines = 2
auto-pairs = true
auto-format = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
g = { a = "code_action" }
D = "delete_char_backward"

# Movement
j = "move_char_left"
";" = "move_char_right"
k = "move_visual_line_up"
l = "move_visual_line_down"

[keys.insert]
# Switch to normal mode
j = { k = "normal_mode" }
l = { l = "move_line_down" }
k = { k = "move_line_up" }

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

# vgld -> delete till the eol from current position
