theme = "github_dark"

[editor]
line-number = "relative"
scroll-lines = 4
auto-pairs = true
auto-format = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
g = { a = "code_action" }
D = "delete_char_backward"

# Movement
j = "move_char_left"
";" = "move_char_right"
k = "move_visual_line_up"
l = "move_visual_line_down"

[keys.insert]
j = { k = "normal_mode" }
S-tab = "unindent"

[keys.select]
j = "extend_char_left"
";" = "extend_char_right"
k = "extend_visual_line_up"
l = "extend_visual_line_down"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
W = [":toggle soft-wrap.enable", ":redraw"]

# vgld -> delete till the eol from current position
